# Generated by Django 4.2.13 on 2026-07-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tenant'], name='channels_tenant__206a20_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_channel_per_tenant'),
        ),
    ]
